language: csharp
solution: ./Notus.sln
install:
  - nuget restore ./Notus.sln
  - nuget install NUnit.ConsoleRunner -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Notus.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Notus.Tests/bin/Release/Notus.Tests.dll
